FORMAT: 1A
HOST: https://api.todomvc.com

# TodoMVC API documentation

TodoMVC API is a Todo storage backend for [TodoMVC](//todomvc.com).

# Data Structures

## Todo (object)
+ id: `42` (number) - The ID of this Todo
+ title: `Find the answer to life, the universe and everything.` (string) - The title of this Todo
+ completed: `true` (boolean) - Whether this Todo is completed or not

# Group Todos

## Todo collection [/todos]

### List all Todos [GET]

+ Response 200 (application/json)
  + Attributes (array[Todo])
  + Body
      ```
      [{
        "id": 42,
        "title": "Find the answer to life, the universe and everything.",
        "completed": false
      }]
      ```

### Create a Todo [POST]

+ Attributes (object)
  + title: `Find the answer to life, the universe and everything.` (string, required) - The title of the Todo

+ Request (application/json)
  + Body
      ```
      {
        "title": "Find the answer to life, the universe and everything."
      }
      ```

+ Response 201 (application/json)
  + Attributes (Todo)
  + Body
      ```
      {
        "id": 42,
        "title": "Find the answer to life, the universe and everything.",
        "completed": false
      }
      ```

### Archive completed Todos [DELETE]

+ Response 204

## Todo entity [/todos/{id}]

+ Parameters
  + id: `42` (number, required) - The ID of the Todo

### Retrieve a Todo [GET]

+ Response 200 (application/json)
  + Attributes (Todo)
  + Body
      ```
      {
        "id": 42,
        "title": "Find the answer to life, the universe and everything.",
        "completed": false
      }
      ```

### Update a Todo [PUT]

+ Attributes (object)
  + title: `Find the answer to life, the universe and everything.` (string) - The title of the Todo
  + completed: `true` (boolean) - Whether the Todo is completed or not

+ Request (application/json)
  + Body
      ```
      {
        "title": "Find the answer to life, the universe and everything.",
        "completed": true
      }
      ```

+ Response 200 (application/json)
  + Attributes (Todo)
  + Body
      ```
      {
        "id": 42,
        "title": "Find the answer to life, the universe and everything.",
        "completed": true
      }
      ```

### Delete a Todo [DELETE]

+ Response 204
